version: '2.2'

services:
  alfresco:
    environment:
      - INDEX=solr6
      - ENABLE_CLUSTERING=true
      - GLOBAL_solr.useDynamicShardRegistration=true

  shard1:
    image: private.docker.xenit.eu/alfresco-enterprise/alfresco-solr6-xenit:2.0.8.2
    container_name: shard1
    ports:
      - 8081:8080
    hostname: shard1
    environment:
      - JAVA_XMX=1024M
      - SOLR_HOST=shard1
      - ALFRESCO_SSL=secret
      - ALFRESCO_SECRET=shared-secret
      - CORES_TO_TRACK=alfresco
      - CORES_ALFRESCO=shard1
      - GLOBAL_ALL_shard.method=DB_ID
      - GLOBAL_ALL_shard.count=2
      - GLOBAL_shard1_shard.instance=0

  shard2:
    image: private.docker.xenit.eu/alfresco-enterprise/alfresco-solr6-xenit:2.0.8.2
    container_name: shard2
    ports:
      - 8082:8080
    hostname: shard2
    environment:
      - JAVA_XMX=1024M
      - SOLR_HOST=shard2
      - ALFRESCO_SSL=secret
      - ALFRESCO_SECRET=shared-secret
      - CORES_TO_TRACK=alfresco
      - CORES_ALFRESCO=shard2
      - GLOBAL_ALL_shard.method=DB_ID
      - GLOBAL_ALL_shard.count=2
      - GLOBAL_shard2_shard.instance=1