version: '2.2'

services:
  alfresco:
    image: ${DOCKER_IMAGE}
    container_name: alfresco    
    environment:
    - SOLR_SSL=none
    - ENABLE_CLUSTERING=true
    - DYNAMIC_SHARD_REGISTRATION=true
    - GLOBAL_local.transform.service.enabled=false
    - DEBUG=true
 #   - GLOBAL_solr.useDebug=false
    volumes:
    - logs:/usr/local/tomcat/logs 
    ports:
    - 8080:8080
    - 8000:8000

  solrlogs:
    image: busybox
    command: [/bin/sh, -c, 'sleep 30 ; tail -n+1 -f /usr/local/tomcat/logs/solrquery.log']
    container_name: solrlogs
    depends_on:
      - alfresco
    volumes:
      - logs:/usr/local/tomcat/logs
    labels:
    - co.elastic.logs/module=json-alfresco
    - eu.xenit.index=solrlogs

  shard1:
    image: hub.xenit.eu/alfresco-enterprise/alfresco-solr6:1.3.0.6
    container_name: shard1
    ports:
      - 8081:8080
    hostname: shard1
    volumes:
      - ./solr/92-init-solr.sh:/docker-entrypoint.d/92-init-solr.sh      
      - ./solr/log4j.properties:/opt/alfresco-search-services/logs/log4j.properties      
      - ./solr/jsonevent-layout-1.7.jar:/opt/alfresco-search-services/solr/server/lib/jsonevent-layout-1.7.jar
      - ./solr/commons-lang-2.6.jar:/opt/alfresco-search-services/solr/server/lib/commons-lang-2.6.jar
      - ./solr/json-smart-1.1.1.jar:/opt/alfresco-search-services/solr/server/lib/json-smart-1.1.1.jar
    labels:
    - co.elastic.logs/module=json
    environment:
    - JAVA_XMX=1024M 
    - SOLR_HOST=shard1
    - ALFRESCO_SSL=none
    - CORES_TO_TRACK=alfresco
    - CORES_ALFRESCO=shard1
    - GLOBAL_ALL_shard.method=DB_ID
    - GLOBAL_ALL_shard.count=2
    - GLOBAL_shard1_shard.instance=0
  
  shard2:
    image: hub.xenit.eu/alfresco-enterprise/alfresco-solr6:1.3.0.6
    container_name: shard2
    ports:
      - 8082:8080
    hostname: shard2
    volumes:
      - ./solr/92-init-solr.sh:/docker-entrypoint.d/92-init-solr.sh
      - ./solr/log4j.properties:/opt/alfresco-search-services/logs/log4j.properties
      - ./solr/jsonevent-layout-1.7.jar:/opt/alfresco-search-services/solr/server/lib/jsonevent-layout-1.7.jar
      - ./solr/commons-lang-2.6.jar:/opt/alfresco-search-services/solr/server/lib/commons-lang-2.6.jar
      - ./solr/json-smart-1.1.1.jar:/opt/alfresco-search-services/solr/server/lib/json-smart-1.1.1.jar
    labels:
    - co.elastic.logs/module=json
    environment:
      - JAVA_XMX=1024M 
      - SOLR_HOST=shard2
      - ALFRESCO_SSL=none
      - CORES_TO_TRACK=alfresco
      - CORES_ALFRESCO=shard2
      - GLOBAL_ALL_shard.method=DB_ID
      - GLOBAL_ALL_shard.count=2
      - GLOBAL_shard2_shard.instance=1


  postgresql:
    image: hub.xenit.eu/public/postgres
    container_name: postgresql
    environment:
      - POSTGRES_USER=alfresco
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alfresco

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.5.0
    container_name: filebeat
    user: root
    restart: unless-stopped
    entrypoint: sh -c "sleep 60 ; filebeat -e"
    labels:
      - co.elastic.logs/enabled=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat/module:/usr/share/filebeat/module
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  logs: