version: '2.2'

services:
  proxy:
    image: hub.xenit.eu/public/haproxy-alfresco:0.0.2
    container_name: proxy
    environment:
    - HAPROXY_INCLUDE_FINDER=true
    - HAPROXY_SERVICE_FINDER=finder
    ports:
    - 80:80

  alfresco:
    image: ${DOCKER_IMAGE}
    container_name: alfresco    
    environment:
    - SOLR_SSL=none
    - GLOBAL_local.transform.service.enabled=false
    - DEBUG=true
 #   - GLOBAL_solr.useDebug=false
    volumes:
    - logs:/usr/local/tomcat/logs 
    ports:
    - 8080:8080
    - 8000:8000

  finder:
    image: hub.xenit.eu/alfred-finder/finder-app:2.2.0-rc.9
    container_name: finder

  solrlogs:
    image: busybox
    command: [/bin/sh, -c, 'sleep 30 ; tail -n+1 -F /usr/local/tomcat/logs/solrquery.log']
    container_name: solrlogs
    depends_on:
      - alfresco
    volumes:
      - logs:/usr/local/tomcat/logs
    labels:
    - co.elastic.logs/module=json-alfresco
    - eu.xenit.index=solrlogs

  postgresql:
    image: hub.xenit.eu/public/postgres
    container_name: postgresql
    environment:
      - POSTGRES_USER=alfresco
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=alfresco

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.5.0
    container_name: filebeat
    user: root
    restart: unless-stopped
    labels:
      - co.elastic.logs/enabled=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat/module:/usr/share/filebeat/module
      - ./filebeat/kibana/dashboards:/usr/share/filebeat/kibana/7/dashboard
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  logs:
