version: '2.2'

services:
  solr:
    image: private.docker.xenit.eu/alfresco-enterprise/alfresco-solr6-xenit:2.0.8.2
    container_name: solr
    volumes:
      - solr:/opt/alfresco/alf_data
    environment:
      - ALFRESCO_HOST=alfresco
      - SOLR_HOST=localhost
      - JAVA_XMS=512M
      - JAVA_XMX=2048M
      - SHARDING=false
      - ALFRESCO_SSL=secret
      - ALFRESCO_SECRET=shared-secret

volumes:
  solr: