version: '3.2'

services:
  elasticsearch:
    #image: elasticsearch:7.5.0
    image: elasticsearch:7.10.1
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
    - 9200:9200
    labels:
      - co.elastic.logs/enabled=false
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./elasticsearch/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
      - ./elasticsearch/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12

  kibana:
    #    image: kibana:7.5.0
    image: kibana:7.10.1
    container_name: kibana
    restart: unless-stopped
    volumes:
      - ./kibana/:/usr/share/kibana/config
    labels:
      - co.elastic.logs/enabled=false
    ports:
      - 5601:5601

