name: build
on:
  push:
    branches:
      - 'master'
      - 'release'
  pull_request:

env:
  ORG_GRADLE_PROJECT_alfresco_nexus_username: ${{ secrets.ALFRESCO_NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_alfresco_nexus_password: ${{ secrets.ALFRESCO_NEXUS_PASSWORD }}
  ORG_GRADLE_PROJECT_cloudsmith_user: ${{ secrets.CLOUDSMITH_USER }}
  ORG_GRADLE_PROJECT_cloudsmith_password: ${{ secrets.CLOUDSMITH_APIKEY }}
  BRANCH_NAME: ${{ github.ref_name }}
  
jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Assemble and check artifacts
        run: ./gradlew build --stacktrace
      - name: Publish
        if: ${{ startsWith(github.ref, 'refs/heads/master') || startswith(github.ref, 'refs/heads/release') }}
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatype_username: ${{ secrets.SONATYPE_S01_USERNAME }}
          ORG_GRADLE_PROJECT_sonatype_password: ${{ secrets.SONATYPE_S01_PASSWORD }}
        run: ./gradlew publish -PsigningKeyId=CDE3528F -i
